### ISSUE TITLE
Freecat won't open!

### ISSUE THREAD

**Issue by snowcatridge10** [JaydenDev/freecat#67]
# Command-line output:

```
PS C:\Users\akreamer\something> git clone https://github.com/JaydenDev/freecat/
Cloning into 'freecat'...
remote: Enumerating objects: 877, done.
remote: Counting objects: 100% (877/877), done.
remote: Compressing objects: 100% (586/586), done.
remote: Total 877 (delta 439), reused 560 (delta 241), pack-reused 0
Receiving objects: 100% (877/877), 1.08 MiB | 1.49 MiB/s, done.
Resolving deltas: 100% (439/439), done.
PS C:\Users\akreamer\something> cd freecat
PS C:\Users\akreamer\something\freecat> npm install
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!

> lzma-native@8.0.1 install C:\Users\akreamer\something\freecat\node_modules\lzma-native
> node-gyp-build


> electron-winstaller@5.0.0 install C:\Users\akreamer\something\freecat\node_modules\electron-winstaller
> node ./script/select-7z-arch.js

Selecting 7-Zip for arch x64

> core-js@2.6.12 postinstall C:\Users\akreamer\something\freecat\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> electron@1.8.2 postinstall C:\Users\akreamer\something\freecat\node_modules\electron-prebuilt-compile\node_modules\electron
> node install.js


> electron@16.0.4 postinstall C:\Users\akreamer\something\freecat\node_modules\electron
> node install.js

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: electron-installer-debian@3.1.0 (node_modules\electron-installer-debian):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for electron-installer-debian@3.1.0: wanted {"os":"darwin,linux","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: electron-installer-redhat@3.3.0 (node_modules\electron-installer-redhat):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for electron-installer-redhat@3.3.0: wanted {"os":"darwin,linux","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 1084 packages from 840 contributors and audited 1128 packages in 24.305s

68 packages are looking for funding
  run `npm fund` for details

found 27 vulnerabilities (2 low, 13 moderate, 9 high, 3 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
PS C:\Users\akreamer\something\freecat> npm start

> freecat@1.0.0 start C:\Users\akreamer\something\freecat
> electron .


App threw an error during load
TypeError: app.whenReady is not a function
    at Object.<anonymous> (C:\Users\akreamer\something\freecat\main\main.js:59:5)
    at Object.<anonymous> (C:\Users\akreamer\something\freecat\main\main.js:83:3)
    at Module._compile (module.js:569:30)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\akreamer\something\freecat\node_modules\electron-compile\lib\require-hook.js:77:14)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at init (C:\Users\akreamer\something\freecat\node_modules\electron-compile\lib\config-parser.js:294:16)
    at main (C:\Users\akreamer\something\freecat\node_modules\electron-prebuilt-compile\lib\es6-init.js:58:29)

```

# OS and dependency versions:

Windows 11
Node v14.13.1
NPM v6.14.8

**Comment by snowcatridge10** [comment]
omg i forgot to run npm install electron --save-dev
